version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"       
    volumes:
      - .:/usr/src/app     
    environment:
      NODE_ENV: development
    depends_on:
      - db                 

  db:
    image: nouchka/sqlite3
    volumes:
      - ./data:/data      
